# Generated by Django 2.0.4 on 2018-05-05 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название')),
                ('desc', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingPopular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='/', null=True, upload_to='products')),
                ('name_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product')),
            ],
        ),
        migrations.AddField(
            model_name='marketingsale',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ProductImg'),
        ),
        migrations.AddField(
            model_name='marketingsale',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product'),
        ),
        migrations.AddField(
            model_name='marketingpopular',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ProductImg'),
        ),
        migrations.AddField(
            model_name='marketingpopular',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product'),
        ),
        migrations.AddField(
            model_name='marketingnew',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ProductImg'),
        ),
        migrations.AddField(
            model_name='marketingnew',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product'),
        ),
    ]
