# Generated by Django 2.0.4 on 2018-05-05 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название Категории')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название продукта')),
                ('short_desc', models.CharField(blank=True, max_length=64, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('img_1', models.ImageField(default=None, null=True, upload_to='products', verbose_name='Фотография')),
                ('img_2', models.ImageField(default=None, null=True, upload_to='products', verbose_name='Фотография только перед')),
                ('img_3', models.ImageField(default=None, null=True, upload_to='products', verbose_name='Фотография только зад')),
                ('marketing', models.IntegerField(default=0, null=True, verbose_name='0=Без маркетинга, 1=Новинки, 2=Популярные, 3=Распродажа')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category', verbose_name='Название Категории')),
            ],
        ),
    ]
