# Generated by Django 2.0.4 on 2018-05-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='marketing',
            field=models.IntegerField(null=True, verbose_name='0=Без, 1=Новинки, 2=Популярные, 3=Распродажа'),
        ),
    ]
