# Generated by Django 2.0.4 on 2018-05-05 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180505_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='marketing',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)], verbose_name='0=Без, 1=Новинки, 2=Популярные, 3=Распродажа'),
        ),
    ]
