# Generated by Django 2.0.4 on 2018-05-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20180505_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='marketing',
            field=models.IntegerField(default=0, null=True, verbose_name='0=Без маркетинга, 1=Новинки, 2=Популярные, 3=Распродажа'),
        ),
    ]
